= olcPixelGameEngine

The olcPixelGameEngine is a single-file prototyping and game-engine framework
created in C++. It is a cross-platform supporting Windows, Linux, and macOS.
The engine is based on the OpenGL rendering API.

NOTE: Starting from olc-pge 2.16 on macOS there is a requirement on the
Objective-C++ runtime. If you use Cmake it means you also need a recent
enough Cmake, at least 3.16.0, to get Objective-C++ support.

== Options

`image_loader`::

Indicates the backend to use for loading image data. For library specific
backends the recipe will automatically add a dependency to the needed
Conan Center package.

* `png` : Uses link:https://conan.io/center/libpng[libpng]. This is the default
	on non-Windows platforms.
* `stb` : Uses link:https://conan.io/center/stb[stb] single-file library.
* `gdi` : The default on Windows, uses system "gdi32" and "gdiplus" libraries.

== License

Uses link:https://raw.githubusercontent.com/OneLoneCoder/olcPixelGameEngine/master/LICENCE.md[OLC-3]
license.

